name: API Build and Test

on:
  pull_request:
    branches:
      - main
    paths:
      - 'api/**'
jobs:
  build_and_test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'

      - name: Build and Test
        run: |
          go build -o traffic-simulation
          ##go test ./...  # placeholder to be modified later
        working-directory: ./api