name: Deploy Database

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          cd database
          docker build -t doroha-postgis .
          cd ..
          docker save doroha-postgis > doroha-postgis.tar

      - name: Transfer Docker image to server
        run:  |
          # Write the SSH private key to a temporary file
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key
          chmod 600 ssh_key
          # Use the temporary file for SCP
          scp -o StrictHostKeyChecking=no -i ssh_key doroha-postgis.tar ${{ secrets.USERNAME }}@165.22.233.166:~/
          # Clean up the temporary key file
          rm ssh_key

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: 165.22.233.166
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /var/www/databases
            mv ~/doroha-postgis.tar /var/www/databases
            docker load < /var/www/databases/doroha-postgis.tar
            docker stop doroha-postgis || true
            docker doroha-postgis || true
            docker run -d -p 5432:5432 -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} doroha-postgis
