name: Deploy Database

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          cd database
          docker build -t doroha-postgis .
          cd ..
          docker save doroha-postgis > doroha-postgis.tar

      - name: Transfer Docker image to server
        run:  |
          # Write the SSH private key to a temporary file
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key
          chmod 600 ssh_key
          # Use the temporary file for SCP
          scp -o StrictHostKeyChecking=no -i ssh_key doroha-postgis.tar ${{ secrets.USERNAME }}@165.22.233.166:~/
          # Clean up the temporary key file
          rm ssh_key

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: 165.22.233.166
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /var/www/databases
            # Remove the existing .tar file, ignore error if it doesn't exist
            rm -f /var/www/databases/doroha-postgis.tar || true
            # Move the new Docker image tar file
            mv ~/doroha-postgis.tar /var/www/databases
            # Stop and remove the existing container if it exists
            docker stop doroha-postgis || true
            docker rm doroha-postgis || true
            # Force remove the old image, even if it's being used
            docker rmi -f doroha-postgis:latest || true
            docker load < /var/www/databases/doroha-postgis.tar
            # Ensure no other containers are using port 5432
            docker ps -q --filter "publish=5432" | xargs -r docker stop
            # Run the new container
            docker run -d -p 5432:5432 -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} doroha-postgis
