name: FE Build and Test

on:
  pull_request:
    branches:
      - main
    paths:
      - 'fe/**'

jobs:
  build_and_test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install
        working-directory: ./fe

      - name: List files in fe directory
        run: ls -alR ./fe

      - name: Build and Test
        run: npm run build
        #npm run test
        working-directory: ./fe
